server:
  port: 8080

spring:
  config:
    import: "optional:configserver:*"
  application:
    name: api-gateway
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      connect-timeout: 2000ms
  cloud:
    gateway:
      routes:
        - id: user-service-public
          uri: lb://user-service
          predicates:
            - Path=/auth/login, /auth/register, /auth/refresh
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@userKeyResolver}"
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/auth/logout, /api/users/**, /api/profile/**, /api/menu/**, /api/announcements/**, /api/algorithm/**, /api/health/**
          filters:
            - name: JwtGatewayFilter
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 5
                key-resolver: "#{@userKeyResolver}"
        - id: admissions-service
          uri: lb://admissions-service
          predicates:
            - Path=/admissions/**, /secretariat/**
          filters:
            - name: JwtGatewayFilter
        - id: dormitory-service
          uri: lb://dormitory-service
          predicates:
            - Path=/camin/**, /student-camin/**
          filters:
            - name: JwtGatewayFilter
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200,http://localhost:4300"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true
